<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

function ncu_theme_defaults() {
    return array(
        'design_preset'              => 'neutral',
        'aggressive_style_takeover'   => 1,
        'style_takeover_preset'       => 'academic-reference',
        'popular_site_template'      => 'academic-red',
        'template_selection_mode'    => 'skin',
        'style_takeover_colors'       => 1,
        'style_takeover_typography'   => 1,
        'style_takeover_text_styles'  => 1,
        'style_takeover_admin'        => 0,
        'style_takeover_respect_optout'=> 1,
        'style_takeover_strict'        => 1,
        'style_takeover_dynamic_bridge'=> 1,
        'style_custom_primary'        => '#B00000',
        'style_custom_secondary'      => '#0B1F3A',
        'style_custom_accent'         => '#E53935',
        'style_custom_surface'        => '#FFFFFF',
        'style_custom_surface_alt'    => '#F7F8FA',
        'style_custom_text'           => '#111827',
        'style_custom_muted'          => '#667085',
        'style_custom_border'         => '#E5E7EB',
        'style_custom_heading_font'   => 'system-sans',
        'style_custom_body_font'      => 'system-sans',
        'style_custom_ui_font'        => 'system-sans',
        'accent_color'               => '#000000',
        'surface_color'              => '#ffffff',
        'text_color'                 => '#000000',
        'muted_color'                => '#5f6368',
        'header_background_color'    => '#ffffff',
        'header_icon_color'          => '#000000',
        'header_border_color'        => '#e5e7eb',
        'footer_background_color'    => '#ffffff',
        'footer_text_color'          => '#000000',
        /* Presentation chrome is opt-in: WordPress/plugin content remains primary. */
        'header_owner_mode'          => 'theme',
        'header_enabled'             => 0,
        'footer_enabled'             => 0,
        'footer_use_managed_by'      => 1,
        'dark_mode_enabled'          => 1,
        'dark_mode_default'          => 'dark',
        'dark_palette'               => 'auto',
        'dark_accent_override'       => '',
        'dark_use_site_accent'        => 1,
        'dark_toggle_enabled'        => 1,
        'dark_floating_toggle'       => 1,
        'dark_toggle_position'       => 'lower_left',
        'fallback_icon_id'           => 0,
        'client_brand_name'          => '',
        'client_logo_id'             => 0,
        'admin_brand_icon_id'        => 0,
        'login_logo_id'              => 0,
        'white_label_enabled'        => 1,
        'admin_style_enabled'        => 1,
        'admin_skin_enabled'         => 1,
        'admin_skin_menu_enabled'    => 1,
        'admin_skin_monochrome'      => 1,
        'frontend_edit_enabled'      => 0,
        'frontend_edit_badges'       => 0,
        'frontend_edit_theme_regions'=> 0,
        'frontend_edit_content'      => 0,
        'frontend_edit_builder'      => 0,
        'frontend_edit_featured'     => 0,
        'admin_skin_mode'            => 'white_future',
        'admin_skin_density'         => 'compact',
        'admin_skin_workspace_bar'   => 0,
        'admin_skin_command_palette' => 1,
        'admin_skin_editor_chrome'   => 1,
        'admin_skin_enhance_tables'  => 1,
        'admin_skin_enhance_modals'  => 1,
        'admin_skin_hide_help_tabs'  => 0,
        'admin_skin_hide_screen_options' => 0,
        'admin_skin_radius'          => 10,
        'admin_skin_shadow'          => 'soft',
        'admin_bar_brand_enabled'    => 0,
        'admin_bar_label'            => '',
        'login_branding_enabled'     => 1,
        'admin_footer_branding'      => 1,
        'hide_wp_dashboard_news'     => 1,
        'managed_by_name'            => '9igeria Online Ltd.',
        'managed_by_url'             => 'https://9igeria.online/',
        'managed_by_logo_id'         => 0,
        'theme_owner_name'           => '9igeria Online Ltd.',
        'theme_owner_url'            => 'https://9igeria.online/',
        'theme_owner_logo_id'        => 0,
        'max_width'                  => 1180,
        'radius'                     => 16,
        'density'                    => 'comfortable',
        'shadow_strength'            => 'soft',
        'sticky_header'              => 1,
        'show_site_tagline'          => 1,
        'show_author_contact'        => 1,
        'elementor_hide_title'       => 1,
        'elementor_content_takeover' => 0,
        'comments_enabled'           => 0,
        'doctor_frontend_enabled'    => 0,
        'drawer_height'              => 92,
        'category_parent'            => 0,
        'category_search'            => 1,
        'header_icon_size'           => 22,
        'header_icon_gap'            => 10,
        'whatsapp_number'            => '',
        'whatsapp_label'             => 'WhatsApp',
        'login_label'                => 'Login',
        'account_label'              => 'My Account',
        'drawer_heading_menu'        => 'Menu',
        'drawer_heading_categories'  => 'Categories',
        'drawer_heading_quick'       => 'Quick Links',
        'footer_text'                => 'Website application managed by 9igeria Online Ltd.',
        'footer_url'                 => 'https://9igeria.online/',
        'footer_image_id'            => 0,
        'quick_actions'              => array(
            array( 'label' => 'Home', 'url' => '/', 'icon' => 'home', 'mode' => 'link', 'content' => '' ),
            array( 'label' => 'Search', 'url' => '/?s=', 'icon' => 'search', 'mode' => 'link', 'content' => '' ),
            array( 'label' => 'About 9Code', 'url' => '/about-us/', 'icon' => 'info', 'mode' => 'link', 'content' => '' ),
            array( 'label' => 'Contact', 'url' => '/contact/', 'icon' => 'mail', 'mode' => 'link', 'content' => '' ),
            array( 'label' => 'Latest', 'url' => '/blog/', 'icon' => 'book-open', 'mode' => 'link', 'content' => '' ),
        ),
        'bottom_actions'             => array(
            array( 'label' => 'Home', 'url' => '/', 'icon' => 'home' ),
            array( 'label' => 'Contact', 'url' => '/contact/', 'icon' => 'mail' ),
            array( 'label' => 'Search', 'url' => '/?s=', 'icon' => 'search' ),
        ),
    );
}

function ncu_theme_core_compatible() {
    if ( ! function_exists( 'ncu_get_settings' ) || ! defined( 'NCU_CORE_API_VERSION' ) || ! defined( 'NCU_THEME_API_VERSION' ) ) { return false; }
    if ( function_exists( 'ncu_core_theme_api_compatible' ) ) { return ncu_core_theme_api_compatible( NCU_THEME_API_VERSION ); }
    return (int) NCU_CORE_API_VERSION === (int) NCU_THEME_API_VERSION;
}

function ncu_theme_settings() {
    if ( ncu_theme_core_compatible() ) { return ncu_get_settings(); }
    return ncu_theme_defaults();
}
