<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Creates the small default 9 Code site only when the theme has not already
 * been configured. Existing pages, categories and homepages are never reset.
 */
add_action( 'init', 'ncu_register_page_category', 20 );
function ncu_register_page_category() {
    if ( taxonomy_exists( 'category' ) ) { register_taxonomy_for_object_type( 'category', 'page' ); }
}

function ncu_starter_category_id() {
    $term = term_exists( '9code', 'category' );
    if ( $term ) { return (int) ( is_array( $term ) ? $term['term_id'] : $term ); }
    $created = wp_insert_term( '9 Code', 'category', array( 'slug' => '9code', 'description' => __( 'The default Nine Code site category.', 'nine-code' ) ) );
    return is_wp_error( $created ) ? 0 : (int) $created['term_id'];
}

function ncu_starter_page( $slug, $title, $content, $category_id ) {
    $existing = get_page_by_path( $slug, OBJECT, 'page' );
    if ( $existing ) { if ( $category_id ) { wp_set_post_terms( $existing->ID, array( $category_id ), 'category', false ); } return (int) $existing->ID; }
    $page_id = wp_insert_post( array( 'post_type' => 'page', 'post_status' => 'publish', 'post_title' => $title, 'post_name' => $slug, 'post_content' => $content, 'comment_status' => 'closed' ), true );
    if ( is_wp_error( $page_id ) || ! $page_id ) { return 0; }
    if ( $category_id ) { wp_set_post_terms( $page_id, array( $category_id ), 'category', false ); }
    return (int) $page_id;
}

function ncu_starter_menu( $pages ) {
    $locations = (array) get_theme_mod( 'nav_menu_locations', array() );
    if ( ! empty( $locations['primary'] ) ) { return; }
    $menu = wp_get_nav_menu_object( '9 Code Main Menu' );
    $menu_id = $menu ? (int) $menu->term_id : wp_create_nav_menu( '9 Code Main Menu' );
    if ( is_wp_error( $menu_id ) || ! $menu_id ) { return; }
    foreach ( $pages as $page_id ) { if ( $page_id ) { wp_update_nav_menu_item( $menu_id, 0, array( 'menu-item-object' => 'page', 'menu-item-object-id' => $page_id, 'menu-item-type' => 'post_type', 'menu-item-status' => 'publish' ) ); } }
    $locations['primary'] = $menu_id; set_theme_mod( 'nav_menu_locations', $locations );
}

function ncu_seed_default_9code_site() {
    if ( ! current_user_can( 'manage_options' ) || get_option( 'ncu_starter_content_4_0_0' ) ) { return; }
    $category_id = ncu_starter_category_id();
    if ( ! $category_id ) { return; }
    $pages = array();
    $pages[] = ncu_starter_page( 'about-us', __( 'About Us — 9 Code', 'nine-code' ), '<!-- wp:paragraph --><p>9 Code is an AI-first publishing and digital site system created to help people organise knowledge, services, authors, categories and useful content in one clear experience.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>What 9 Code helps you do</h2><!-- /wp:heading --><!-- wp:list --><ul><li>Present people, ideas, learning, services and publications clearly.</li><li>Connect structured fields with human editing and responsible AI workflows.</li><li>Build a site that remains simple for visitors and powerful for its administrator.</li></ul><!-- /wp:list --><!-- wp:heading {"level":2} --><h2>Our approach</h2><!-- /wp:heading --><!-- wp:paragraph --><p>We begin with the purpose of the site, organise its people and content, and then provide simple tools for managing the details. AI assists the work, but the site owner remains in control of the fields, instructions, approvals and final publication.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>This site is powered by Nine Code and managed by 9igeria Online Limited.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'services', __( 'Services', 'nine-code' ), '<!-- wp:paragraph --><p>Explore practical digital services for building, organising and improving a professional online presence.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Our services</h2><!-- /wp:heading --><!-- wp:list {"className":"is-style-ncu-clean-list"} --><ul class="is-style-ncu-clean-list"><li><strong>AI-assisted website planning:</strong> turn a goal into pages, fields, categories and a clear workflow.</li><li><strong>WordPress site development:</strong> create professional pages, custom post types and mobile-first templates.</li><li><strong>Author and knowledge systems:</strong> organise lecturers, professionals, services, courses, publications and ideas.</li><li><strong>ACF and structured data management:</strong> manage fields, taxonomy relationships, backups and safe imports.</li><li><strong>Site presentation and improvement:</strong> refine layout, colour, typography, accessibility and responsive behaviour.</li></ul><!-- /wp:list --><!-- wp:heading {"level":2} --><h2>How to begin</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Choose the service that fits your goal, send the site administrator a short description of what you need, and we will help define the next practical step.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'sample-solutions', __( 'Sample Solutions', 'nine-code' ), '<!-- wp:paragraph --><p>These examples show the kind of practical solution that can be planned and delivered through the 9 Code approach. Every example is editable and can be adapted to a real organisation.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Solution 1 — Professional profile and knowledge site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A lecturer, coach or professional can present a clear profile, qualifications, specialisations, articles, courses, services and contact options in one organised site.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Solution 2 — Course and learning site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A learning site can organise lecturers, courses, lessons, resources, assessments and learner access while keeping the lecturer’s identity visible.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Solution 3 — Conference and event site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A conference site can present the theme, presenters, programme, fees, registration, submissions, reviews, proceedings and certificates in a guided sequence.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Solution 4 — Service and payment site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>A service site can explain an offer, show the expected outcome, guide the customer to contact the provider, and then collect payment only after the offer has been understood.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Replace these examples with your own completed solutions, screenshots, links and results.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'active-sites', __( 'Active Sites', 'nine-code' ), '<!-- wp:paragraph --><p>This page is the public directory of active sites managed through the 9 Code system. Add, remove or rearrange a site whenever your portfolio changes.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>9igeria Online</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong>Purpose:</strong> a digital home for services, knowledge, publishing and connected projects. <strong>Status:</strong> Active.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Learning and course sites</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong>Purpose:</strong> present lecturers, courses, lessons and useful learning resources. <strong>Status:</strong> Active and growing.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Conference and event sites</h2><!-- /wp:heading --><!-- wp:paragraph --><p><strong>Purpose:</strong> publish event information, registration, submissions, programme details and proceedings. <strong>Status:</strong> Active when an event is open.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Add a site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>For each new site, add its name, purpose, owner, current status, featured image and approved public URL. Keep this directory accurate so visitors see only active destinations.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'contact-us', __( 'Contact Us', 'nine-code' ), '<!-- wp:paragraph --><p>We welcome questions about 9 Code, website development, structured content, learning systems, publishing and connected digital services.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Contact options</h2><!-- /wp:heading --><!-- wp:list --><ul><li><strong>Website:</strong> 9igeria Online and its managed project sites.</li><li><strong>WhatsApp:</strong> use the configured WhatsApp button in the site header when a number has been added.</li><li><strong>Email:</strong> use the site administrator’s approved contact address configured in WordPress.</li><li><strong>Message:</strong> state your name, the service or site you are asking about, and the outcome you need.</li></ul><!-- /wp:list --><!-- wp:heading {"level":2} --><h2>Before you send a request</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Include enough information for us to understand the goal. For a website request, describe the audience, content type, deadline, existing materials and preferred next step. Do not send passwords, API keys or private payment information in a public message.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>The site administrator can edit this page with the correct email address, telephone number, WhatsApp link, office address and contact form.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'make-payment', __( 'Make Payment', 'nine-code' ), '<!-- wp:paragraph --><p>Use this page only after the service, price, deliverables and payment instructions have been confirmed by the site administrator.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>Payment steps</h2><!-- /wp:heading --><!-- wp:list {"ordered":true} --><ol><li>Choose or confirm the service you want.</li><li>Ask for the current quotation or invoice reference.</li><li>Confirm the approved amount, payment method and recipient details.</li><li>Make payment through the approved bank, card or online gateway.</li><li>Send the payment reference with your name and invoice number through the approved contact channel.</li></ol><!-- /wp:list --><!-- wp:heading {"level":2} --><h2>Payment record</h2><!-- /wp:heading --><!-- wp:table --><figure class="wp-block-table"><table><tbody><tr><td>Customer name</td><td>Enter customer name</td></tr><tr><td>Service</td><td>Enter service name</td></tr><tr><td>Invoice/reference</td><td>Enter approved reference</td></tr><tr><td>Amount</td><td>Enter confirmed amount and currency</td></tr><tr><td>Date paid</td><td>Enter payment date</td></tr></tbody></table></figure><!-- /wp:table --><!-- wp:paragraph --><p><strong>Important:</strong> edit this page with the correct payment account or gateway before publishing it. Visitors should never rely on payment details that have not been verified by the site owner.</p><!-- /wp:paragraph -->', $category_id );
    $pages[] = ncu_starter_page( 'terms-and-conditions', __( 'Terms and Conditions', 'nine-code' ), '<!-- wp:paragraph --><p>These terms explain the basic conditions for using this site and requesting services from the site owner. Edit them to match the exact organisation, jurisdiction and services before relying on them as a final legal document.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>1. Using this site</h2><!-- /wp:heading --><!-- wp:paragraph --><p>You may browse and use the public information on this site for lawful purposes. Do not misuse the site, interfere with its operation, attempt unauthorised access, or submit content that is unlawful, harmful or misleading.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>2. Services and information</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Service descriptions, prices, availability and delivery times may change. A service becomes confirmed only when the site owner has accepted the request and communicated the applicable terms, deliverables and price.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>3. Payments and refunds</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Payment instructions must be confirmed through an approved contact channel. Refund, cancellation and rescheduling rules should be agreed before payment and recorded with the relevant invoice or order reference.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>4. User information</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Provide accurate information and do not send passwords, API keys or unnecessary sensitive data through public forms or messages. The site owner should publish a separate privacy notice describing how personal information is handled.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>5. Intellectual property</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Unless stated otherwise, the site’s text, branding, design and original materials belong to the site owner or its licensors. Do not reproduce or redistribute protected material without permission.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>6. External links and availability</h2><!-- /wp:heading --><!-- wp:paragraph --><p>External links are provided for convenience. The site owner does not guarantee the content or availability of external services and may temporarily change, suspend or improve this site.</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2>7. Contact and updates</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Questions about these terms should be sent through the Contact Us page. The site owner may update these terms by publishing a revised version with a new effective date.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>Effective date:</strong> enter the date these terms become active.</p><!-- /wp:paragraph -->', $category_id );
    ncu_starter_menu( $pages );
    $about = ! empty( $pages[0] ) ? $pages[0] : 0;
    if ( $about && 'page' !== get_option( 'show_on_front' ) && ! get_option( 'page_on_front' ) ) { update_option( 'show_on_front', 'page' ); update_option( 'page_on_front', $about ); }
    if ( 1 === (int) get_option( 'default_category', 1 ) ) { update_option( 'default_category', $category_id ); }
    update_option( 'ncu_starter_content_4_0_0', array( 'category_id' => $category_id, 'about_page_id' => $about, 'created_at' => current_time( 'mysql' ) ), false );
}
add_action( 'after_switch_theme', 'ncu_seed_default_9code_site' );
add_action( 'admin_init', 'ncu_seed_default_9code_site' );
